// 登录后保存用户信息
export const SAVE_USER_DATA = 'SAVE_USER_DATA';

// 医生界面保存患者信息
export const SAVE_PATIENT_DATA = 'SAVE_PATIENT_DATA';
export const CHOOSE_ONE_DISEASE = 'CHOOSE_ONE_DISEASE';
export const SAVE_ALL_SYMPTOMS = 'SAVE_ALL_SYMPTOMS';
export const SAVE_CHOOSE_SYMPTOMS = 'SAVE_CHOOSE_SYMPTOMS';